config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/', to:'tasks#index', as: 'root_url'
  get 'tasks/new', to: 'tasks#new', as: 'new_task'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  post 'tasks/new', to: 'tasks#create', as: 'create_task'
  put 'tasks/update/:id', to: 'tasks#update', as: 'update_task'
  delete 'tasks/delete/:id', to: 'tasks#delete', as: 'del_task'

  # resources :tasks do
  #   get 'new', to: 'tasks#new'
  #   post 'create', to: 'tasks#create'
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
    render 'tasks/index'
  end

  def create
    Task.create( task_create_params)
    redirect_to '/'
  end

  def update
    task = Task.find_by(id: params[:task][:id])
    if task
      task.update!( task_update_params)
      redirect_to '/'
    end

  end

  def edit
    @task = Task.find_by(id: params[:id])
    unless @task
      redirect_to '/'
    end
  end

  def delete
    task = Task.find_by(id: params[:id])
    if task
      task.destroy!
    end
    redirect_to '/'
  end

  def task_create_params
    params.require(:task).permit(:name, :description, :user_id)
  end

  def task_update_params
    params.require(:task).permit(:name, :description, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crud</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/tasks/edit.html.erb
<div>
  <% if user_signed_in? %>
      <span>Здравствуйте, <%= current_user.email %></span>
      <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
  <% else %>
      <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Регистрация', new_user_registration_path %>
  <% end %>
</div>
<hr>

<div>
  <%= form_for(@task, url: update_task_path(@task), html: {method: "put"}) do |t|%>
      <%= t.hidden_field :id %>
      <%= t.hidden_field :user_id, :value => current_user.id %>
      <%= t.text_field :name %> <br>
      <%= t.text_field :description %> <br>
      <%= t.submit "Save" %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div>
  <% if user_signed_in? %>
      <span>Здравствуйте, <%= current_user.email %></span>
      <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
  <% else %>
      <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Регистрация', new_user_registration_path %>
  <% end %>
</div>
<hr>

<%if current_user %>
<div>
  <%= link_to 'New task', 'tasks/new' %>
  <% @tasks.each do |task| %>
    <% if (task.user_id == current_user.id)  %>
      <div>
        <%= task.name %>
        <%= link_to 'Update', edit_task_path(id: task.id) %>
        <%= link_to 'Delete', del_task_path(id: task.id), method: :delete %>
      </div>
    <% end %>
  <% end %>
</div>
<% end %>

app/views/tasks/new.html.erb
<div>
  <% if user_signed_in? %>
      <span>Здравствуйте, <%= current_user.email %></span>
      <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
  <% else %>
      <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Регистрация', new_user_registration_path %>
  <% end %>
</div>
<hr>

<div>
  <%= form_for :task do |f|-%>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <%= f.text_field :name, placeholder: 'name' %>
      <%= f.text_field :description, placeholder: 'description' %>
      <%= f.submit "save" %>
  <% end %>
</div>